services:
  - type: web
    name: codetimemachine-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: CLIENT_URL
        sync: false
